name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.8
  provider: ^6.0.5
  weather_repository:
    path: packages/weather_repository
  db:
    path: packages/db
  weather_animation: ^0.0.2
  flutter_typeahead: ^4.6.2
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true