name: open_weather_map_provider
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.1
  weather_api:
    path: ../weather_api

dev_dependencies:
  build_runner: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
